### PR TITLE
Create Botway CE

### PR DESCRIPTION
**Pull request by abdfnx**

### CODE REVIEW

**Review by MichaelYuhe — COMMENTED** [review]
Can you explain what botway is with a more clear description?
Now the description maybe confusing if a user hasn't heard botway before.

**Comment by abdfnx** [comment]
> Can you explain what botway is with a more clear description? Now the description maybe confusing if a user hasn't heard botway before.

So Botway CE is a part of botway, it's a code editor that have all the tools and packages that the user needs, it's just for botway users

**Review by MichaelYuhe — APPROVED** [review]

**Comment by MichaelYuhe** [comment]
> > Can you explain what botway is with a more clear description? Now the description maybe confusing if a user hasn't heard botway before.
> 
> So Botway CE is a part of botway, it's a code editor that have all the tools and packages that the user needs, it's just for botway users

LGTM. Can you also help to write a documentation about how to deploy Botway CE and the basic configuration? I believe that would help botway users and let other users can start to try Botway.

**Comment by abdfnx** [comment]
> > > Can you explain what botway is with a more clear description? Now the description maybe confusing if a user hasn't heard botway before.
> > 
> > So Botway CE is a part of botway, it's a code editor that have all the tools and packages that the user needs, it's just for botway users
> 
> LGTM. Can you also help to write a documentation about how to deploy Botway CE and the basic configuration? I believe that would help botway users and let other users can start to try Botway.

Don't worry, it's on the roadmap

**Pull request merged**
