### PR TITLE
app: add grafana

### PR DESCRIPTION
**Pull request by CorrectRoadH**

### CODE REVIEW

**Comment by yuaanlin** [comment]
@CorrectRoadH No data directory? All settings will reset after service restart!

**Comment by CorrectRoadH** [comment]
> @CorrectRoadH No data directory? All settings will reset after service restart!

https://hub.docker.com/r/grafana/grafana 😭 The docs don't mention this. I will find out the data directory

**Comment by yuaanlin** [comment]
> > @CorrectRoadH No data directory? All settings will reset after service restart!
> 
> https://hub.docker.com/r/grafana/grafana 😭 The docs don't mention this. I will find out the data directory

https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#use-persistent-storage-recommended

**Comment by CorrectRoadH** [comment]
> > > @CorrectRoadH No data directory? All settings will reset after service restart!
> > 
> > 
> > https://hub.docker.com/r/grafana/grafana 😭 The docs don't mention this. I will find out the data directory
> 
> https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#use-persistent-storage-recommended

please take a look again

**Review by yuaanlin — APPROVED** [review]

**Pull request merged**
