### PR TITLE
Add Halo to marketplace

### PR DESCRIPTION
**Pull request by ruibaby**
Added [Halo](https://github.com/halo-dev/halo) to Marketplace list.

By the way, do I need to test? Currently I don't know how to make usage tests, Thanks.

### CODE REVIEW

**Review by yuaanlin — APPROVED** [review]
Thanks for your contribution! We currently do not support tests for marketplace drafts. If there are any issues after the PR is merged, we will help you fix them 😂

By the way, after this PR is merged, please write documentation to help other users deploy this awesome service!

**Comment by yuaanlin** [comment]
Good news! This marketplace service is working perfectly 🎉

Screenshot 2023-05-04 at 5 33 45 PM

Screenshot 2023-05-04 at 5 34 32 PM

**Comment by ruibaby** [comment]
@yuaanlin 

Nice！I will add documentation later.

**Comment by MichaelYuhe** [comment]
Thanks for contribution! What an amazing project!

**Pull request merged**
