### PR TITLE
Update django.zh-CN.mdx

### PR DESCRIPTION
**Pull request by josephgu41**

### CODE REVIEW

**Review by pan93412 — COMMENTED** [review]
It may be better to translate it to Chinese (T) and English :D

**Review by pan93412 — APPROVED** [review]

**Comment by josephgu41** [comment]
Okay, I will pay attention next time.

**Comment by josephgu41** [comment]
I'm very sorry, I am new to pull requests. If it's convenient, could you tell me how I can submit a PR better?

**Comment by MichaelYuhe** [comment]
Thanks for your contribution!

**Pull request merged**
