### PR TITLE
add issue template

### PR DESCRIPTION
**Pull request by Undertone0809**
let's add some issue templates for developer.

Like this:

image

image

https://github.com/Undertone0809/promptulate This project as a reference.

### CODE REVIEW

**Comment by MichaelYuhe** [comment]
This repo is just for documentation, prebuilt marketplace and locales, I think it's unnecessary to use an issue template like this one. Thanks for the idea and contribution. cc @yuaanlin @pan93412 any thoughts on that?

**Comment by Undertone0809** [comment]
Thanks for review！There are some people will send questions here, and templates will reduce communication costs.

**Comment by pan93412** [comment]
> Thanks for review！There are some people will send questions here, and templates will reduce communication costs.

We use Discord as the main feedback channel. GitHub is for improving documentation and prebuilt features, not for reporting platform issues IMO.

**Comment by pan93412** [comment]
How about creating a template for reporting prebuilt suggestions, bugs, and enhancements or issues in documentation?

**Comment by MichaelYuhe** [comment]
> How about creating a template for reporting prebuilt suggestions, bugs, and enhancements or issues in documentation?

Yes it will be a better solution!

**Review by MichaelYuhe — APPROVED** [review]
LGTM! cc @yuaanlin for review

**Review by yuaanlin — APPROVED** [review]
Thanks for contribution 🚀

**Pull request merged**
