### PR TITLE
feat: add slidev to marketplace

### PR DESCRIPTION
**Pull request by Alkaidcc**
add [slidev](https://sli.dev) to marketplace. BTW, I don't know how to test to make it working

### CODE REVIEW

**Comment by MichaelYuhe** [comment]
Sorry that we're still working on the test feature. LGTM!

**Comment by yuaanlin** [comment]
Hello, thank you for your contribution! However, it appears that [Slidev](https://sli.dev/) may not be the best fit for the marketplace, as it requires users to manually write or copy markdown files to a directory rather than providing a web-based GUI for interaction. As a result, users who deploy Slidev from the marketplace will only be able to view the example slides and won't be able to modify them 😂

Perhaps for Slidev, we could consider implementing a basic GUI that allows users to create their slides without having to directly edit the files?

**Comment by Alkaidcc** [comment]
Sometimes, people only need [static hosting services](https://sli.dev/guide/hosting.html#static-hosting), such as Netlify or Vercel. Has Zeabur already supported it?

**Comment by yuaanlin** [comment]
> Sometimes, people only need [static hosting services](https://sli.dev/guide/hosting.html#static-hosting), such as Netlify or Vercel. Has Zeabur already supported it?

If Zeabur detects that a project is utilizing a static frontend framework such as Vite, Create React App, or Vue CLI, it will automatically deploy the project using static hosting, which reduces the billing to zero.

Maybe we can simply treat Slidev as another static frontend framework!

**Comment by Alkaidcc** [comment]
It seems that we need a **slidev-template** instead of marketplace add-on.

**Comment by yuaanlin** [comment]
> It seems that we need a **slidev-template** instead of marketplace add-on.

Actually, it's here! https://github.com/zeabur/slidev-template 😂

**Pull request closed without merging**
