### PR TITLE
Create ttrss.json

### PR DESCRIPTION
**Pull request by sseaan**

### CODE REVIEW

**Review by MichaelYuhe — APPROVED** [review]
LGTM. Thanks for your contribution!
But it may need a deploy document because it need a PostgreSQL and create a database for it. Can you help us write the document just like [this one](https://zeabur.com/docs/marketplace/n8n)? Otherwise other users would be confused when deploying ttrss

**Comment by MichaelYuhe** [comment]
cc @pan93412 for further review

**Comment by sseaan** [comment]
> OK, I'll do that. Since this project also has a built-in Mercury Parser API plugin, I'll document that as well

**Comment by sseaan** [comment]
> LGTM. Thanks for your contribution! But it may need a deploy document because it need a PostgreSQL and create a database for it. Can you help us write the document just like [this one](https://zeabur.com/docs/marketplace/n8n)? Otherwise other users would be confused when deploying ttrss

OK, I'll do that. Since this project also has a built-in Mercury Parser API plugin, I'll document that as well

**Comment by MichaelYuhe** [comment]
> > LGTM. Thanks for your contribution! But it may need a deploy document because it need a PostgreSQL and create a database for it. Can you help us write the document just like [this one](https://zeabur.com/docs/marketplace/n8n)? Otherwise other users would be confused when deploying ttrss
> 
> OK, I'll do that. Since this project also has a built-in Mercury Parser API plugin, I'll document that as well

Thanks a lot!

**Pull request merged**
